@startuml
'https://plantuml.com/class-diagram

abstract class InputStream

InputStream <|-- FileInputStream

InputStream <|-- StringBufferInputStream
InputStream <|-- ByteArrayInputStream
InputStream <|-- FilterInputStream

FilterInputStream <|-- BufferInputStream
FilterInputStream <|-- DataInputStream
FilterInputStream <|-- LineNumberInputStream


@enduml