@startuml
'https://plantuml.com/class-diagram

abstract class Phone
interface Brand

abstract class Phone {
open(): void
close(): void
call(): void
}

Client ..> Phone
Client ..> Brand
Phone o- Brand
FlodedPhone --|> Phone
UpRightPhone --|> Phone
Xiaomi --|> Brand
Vivo --|> Brand

@enduml