@startuml
'https://plantuml.com/class-diagram

interface Voltage5V
class Client

class VoltageAdapter {

}

abstract class Voltage220V {
output220V(): void
}

class Phone {
charge(): void
}

Voltage5V <|-- VoltageAdapter
Voltage220V <|-- VoltageAdapter
Voltage5V <.. Phone
VoltageAdapter <.. Client
Phone <.. Client

@enduml