@startuml
'https://plantuml.com/class-diagram

interface Iterator

class CSCollegeIterator
class InfoCollegeIterator

Iterator <|-- CSCollegeIterator
Iterator <|-- InfoCollegeIterator

abstract class College

College <|-- CSCollege
College <|-- InfoCollege

CSCollege .. CSCollegeIterator
InfoCollege .. InfoCollegeIterator

@enduml