@startuml
'https://plantuml.com/class-diagram

class DispatchServlet {
doDispatch(): void
}

interface Controller

class HttpController

class SimpleController

class AnnotationController

Controller <|-- HttpController
Controller <|--- SimpleController
Controller <|-- AnnotationController


class SimpleAdapter
class HttpAdapter
class AnnotationAdapter

interface HandlerAdapter
HandlerAdapter <|-- SimpleAdapter
HandlerAdapter <|-- HttpAdapter
HandlerAdapter <|-- AnnotationAdapter

DispatchServlet o- HandlerAdapter
Controller <---- DispatchServlet


SimpleController <-- SimpleAdapter
HttpController <-- HttpAdapter
AnnotationController <-- AnnotationAdapter

@enduml