@startuml
'https://plantuml.com/class-diagram

class TeacherDao {
teach():void
}

interface ITeacherDao {
teach():void
}

class TeacherDaoProxy {
teach():void
}

ITeacherDao <|-- TeacherDao
ITeacherDao <|-- TeacherDaoProxy
TeacherDaoProxy o-- TeacherDao

Client --> TeacherDaoProxy

@enduml